# Hauptmenü
[[main]]
name = "Startseite"
url = "/"
weight = 1

[[main]]
name = "Team"
url = "team/"
weight = 3

[[main]]
name = "Leistungen"
url = "leistungen/"
weight = 2

[[main]]
name = "Projekte"
url = "projekte/"
weight = 4

# Fußzeilenmenü
[[footer]]
name = "Team"
url = "team/"
weight = 1

[[footer]]
name = "Datenschutz"
url = "datenschutz/"
weight = 2

[[footer]]
name = "Kontakt"
url = "kontakt/"
weight = 5

[[footer]]
name = "Impressum"
url = "impressum/"
weight = 6
