# Hauptmenü
[[main]]
name = "Startseite"
url = "/"
weight = 1

[[main]]
name = "Über Uns"
url = "ueber-uns/"
weight = 2

[[main]]
name = "Dienstleistungen"
url = "dienstleistungen/"
weight = 3
hasChildren = true

[[main]]
parent = "Dienstleistungen"
name = "Abriss"
url = "dienstleistungen/abriss/"
weight = 1

[[main]]
parent = "Dienstleistungen"
name = "Abriss1"
url = "dienstleistungen/abriss1/"
weight = 2

[[main]]
name = "Projekte"
url = "projekte/"
weight = 4


# Fußzeilenmenü
[[footer]]
name = "Über Uns"
url = "ueber-uns/"
weight = 1

[[footer]]
name = "Datenschutzrichtlinie"
url = "datenschutzrichtlinie/"
weight = 2



[[footer]]
name = "Kontakt"
url = "kontakt/"
weight = 5

[[footer]]
name = "Impressum"
url = "impressum/"
weight = 6
